banner:
    location: classpath:/auxiliares/banner.txt
    
spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/sigecu1?useSSL=false
    username: root
    password: root
=======
    url: jdbc:mysql://localhost:3306/sigecu_spring_boot?useSSL=false
    username: root
    password: 
>>>>>>> master


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      
    
  thymeleaf:
    cache: false